### ISSUE TITLE
Large-scale datasets

### ISSUE THREAD

**Issue by mnikitin** [mk-minchul/AdaFace#22]
Hello!
Thank you for your incredible work! Analysis of margin losses through gradient scaling term is quite eye-opening.

My questions are:
1. Why didn't you provide any experiments' results for some really large-scale datasets, like WebFace42M?
2. Any observations or thoughts about stability of AdaFace under noisy labels, compared to default losses like CosFace/ArcFace ?

**Comment by mk-minchul** [comment]
Hi mnikitin. Thanks for the interest in the paper.
1. The training of WebFace42M requires large memory GPU since there are 2M number of identities (causing the last FC layer to be huge). We are currently looking into training the model with WebFace42M for a release and it may take some time. 
2. As for the label noise, AdaFace, CosFace and ArcFace handles the label noise inadequately. Of the many kinds of label noise, such as label flip (switching the label within the known identities), unseen identity or unidentifiable image, AdaFace handles the unidentifiability aspect. AdaFace adaptively puts a strong emphasis on samples with large cosine distance to the ground truth center, when the samples' image quality is high. This could imply that the effect of label flip of high quality samples could be more severe than the other two.

**Comment by mnikitin** [comment]
@mk-minchul 

1. Ok, great! Looking forward to the results.
2. Thanks! So it looks like AdaFace could be more sensitive to label flip and unseen identities, compared to CosFace and ArcFace, since it puts especially high emphasis on hard samples

**Comment by thucth-qt** [comment]
Hi @mk-minchul, 
Did you finish the experiment on  WebFace42M? Could you please update the source code to train the model with this largescale dataset so that I can do training meanwhile (the current source code is not suitable for training on a large-scale dataset because of OMM trouble)?
Thanks

**Comment by NNDam** [comment]
For (ultra) large scale dataset can we use PartialFC + Adaface ? I've already modified PartialFC for using with Adaface, looklike it's converging but will take sometime to get final result and compare with previous trained model using CosFace (my dataset is 5M ids + 105M images, training with 2xA100)

**Comment by twmht** [comment]
@NNDam 

can you share code with PartialFC? I just modified from insightface but can't coverage.
